### ISSUE TITLE
MVP: base data model (graph) + app

### ISSUE THREAD

**Issue by halcyondude** [cncf/landscape-graph#32]
### Scope for Minimum Viable Product (MVP)

- [x] cncf/landscape-graph#38
- [x] import --> Neo4j database (via cypher), base entities in place
- [x] cncf/landscape-graph#7
- [ ] minimal web based UI to explore graph
- [ ] JavaFX native app (running Neo4j in embedded mode)

### Stretch Goals
- [ ] cncf/landscape-graph#40
- [ ] #53
