### ISSUE TITLE
k8s: Create Kubernetes Deployment (basic, merely helm)

### ISSUE THREAD

**Issue by halcyondude** [cncf/landscape-graph#70]
## Tasks

This is a "just make it go now" task.  Later we'll follow up with the Landscape Graph Kubernetes Operator.

- [ ] local developer setup w/ kind
- [ ] serious / HA (3 node causal clustering) setup
    - [ ] multi-node kind
    - [ ] other cluster(s) - CIL/GKE/EKS/AKS
- [ ] example helm deployment --> kind
- [ ] create GitHub Action, or using existing bits to create CI based on GH Action --> runner (kind, neo4j)
- [ ] use flux2 for all deployments
- [ ] MAKE USER FACING DOCS SO NEW CONTRIBUTORS CAN...CONTRIBUTE

https://medium.com/neo4j/how-to-set-up-gitops-for-a-full-stack-app-with-flux-helm-on-kubernetes-7ec88664bad2
