### ISSUE TITLE
Kubernetes Operator: landscape-graph-operator

### ISSUE THREAD

**Issue by halcyondude** [cncf/landscape-graph#71]
_this issue exists to largely be a handy place to create issues w/ a single click :)_

# Kubernetes Operator for Landscape Graph

## Tasks

- [ ] Turn what's below into issues.  Thank you GH UI :)

- [ ] Create Repo --> cncf/landscape-graph-operator
- [ ] scaffold out a new operator
    - [ ] kubebuilder based
        - best --> https://github.com/vmware-tanzu-labs/operator-builder for reasons
    - [ ] (perhaps?) Java based operator
        - https://developers.redhat.com/articles/2022/02/15/write-kubernetes-java-java-operator-sdk
        -  https://github.com/java-operator-sdk/java-operator-sdk
        - https://javaoperatorsdk.io/
 
## Operator Scope & Requirements

- [ ] Applications & Services
    - [ ] neo4j enterprise
    - [ ] bloom enterprise, w/ GH auth (if possible, else other)
    - [ ] GraphQL endpoint
    - [ ] front door(s)
    - [ ] src-d/gitbase
    - [ ] various cron / batch jobs

- [ ] Operations & Observability
    - [ ] linkerd
    - [ ] observability stack 
        - [ ] (starting position for alacrity - OTel Collector, Fluentd, Grafana, Cortex, Loki, (Jaeger || Tempo))

- [ ] Security & Connectivity
    - [ ] SSO / OIDC (spiffe? oauth2-proxy?)
    - [ ] cert-manager, LetsEncrypt
    - [ ] external-dns
    - [ ] Secrets mgmt (suggest: [external-secrets](https://github.com/external-secrets/external-secrets), [external-secrets.io](https://external-secrets.io/)
    - [ ] proper RBAC, including Service Accounts for all services (no default SA!!!)
